### ISSUE TITLE
Playlist issues

### ISSUE THREAD

**Issue by brendan-pike** [ArturSierzant/OMPD#118] opened 2020-02-06 02:40 UTC
I've found some bugs in playlists;
1. If you create a new empty playlist from the /favorite.php view you are not able to add songs to this playlist from the playing now or album view
2. When updating an album any tracks from that album are removed from your playlists
3. When updating an album that contains tracks in a playlist that playlist is no longer visible to add new tracks to in the Now Playing view.

**Comment by ArturSierzant** [comment] 2020-02-07 15:23
Thanks for testing :)

1. Fixed in 59b40c5
2. I can't reproduce this... By 

> any tracks from that album are removed from your playlists 

you mean favorite playlist? When I update album that has some tracks added to any favorites playlists, that tracks remain on these playlists after update. It's secured in:
 https://github.com/ArturSierzant/OMPD/blob/59b40c5f3439498b660c4c0b498215d77e8f8c8f/update.php#L1277-L1284

3. I don't know if this is a case I'm thinking about, but I attentionally removed playlist from list when track was already added to it. In latest commit I changed that, so the playlist is listed, but is marked with '[&#9673;]'. It works only for local files - not for streams (yet...).

Regards,
Artur

**Closed** 2024-09-18 13:24 UTC
