### ISSUE TITLE
Favourites page covered by persistent loading spinner 

### ISSUE THREAD

**Issue by tomchiverton** [ArturSierzant/OMPD#161] opened 2023-05-03 15:17 UTC
How can I find out what is causing the spinner to appear ?

[
![Screenshot_20230503-161643](https://user-images.githubusercontent.com/684204/235960749-d1d97da1-2bf7-4ae8-a82a-e9adf85481d5.png)
](url)

**Comment by ArturSierzant** [comment] 2023-05-04 08:03
Hi,
try to open this page in browser on PC and use developer tool (press F12). There is probably error in java script and that's why spinner doesn't disappear.

**Comment by tomchiverton** [comment] 2023-05-04 16:51
Wasn't there when went to recheck, despite persisting for days

**Comment by tomchiverton** [comment] 2023-05-22 09:27
Happening again, No error in developer tools console, no failed requests in network log.

Occurs for both anonymous and admin users.

**Comment by tomchiverton** [comment] 2023-05-22 09:28
I've deleted everything from session and update_status tables, and re-ran a "Update whole media directory". Took ~2 minutes and made no difference.

**Comment by tomchiverton** [comment] 2023-05-22 11:18
I think there is a mistake in each theme - https://github.com/ArturSierzant/OMPD/pull/163

**Comment by ArturSierzant** [comment] 2023-05-23 19:58
Thanks for your solution. I see it prevents displaying spinner for some more pages. But the problem is: why doesn't the spinner disappear in your case? It should be switched off by calling `hideSpinner()` in `footer.inc.php` (line 55). Unfortunately I can't reproduce this issue on my system. Maybe you will be able to :) ?

**Comment by tomchiverton** [comment] 2023-05-26 10:11
I never seem to get the footer output, when the bug occurs.

That last few lines in view source are

```
<tr class="even mouseover">
	
	<td><a href="javascript:ajaxRequest('play.php?action=playSelect&amp;favorite_id=21&amp;menu=favorite',evaluateAdd);" onMouseOver="return overlib('Play');" onMouseOut="return nd();"><i id="play_21" class="fa fa-play-circle-o fa-fw icon-small"></i></a></td>
	
	<td><a href="javascript:ajaxRequest('play.php?action=addSelect&amp;favorite_id=21&amp;menu=favorite',evaluateAdd);" onMouseOver="return overlib('Add to playlist');" onMouseOut="return nd();"><i id="add_21" class="fa fa-plus-circle fa-fw icon-small"></i></a></td>
	
	<td><a href="[stream.php?action=playlist&amp;favorite_id=21&amp;stream_id=-1](view-source:http://mp3.house/stream.php?action=playlist&favorite_id=21&stream_id=-1)" onMouseOver="return overlib('Stream');" onMouseOut="return nd();"><i class="fa fa-rss fa-fw icon-small"></i></a></td>
	
	<td><a href="javascript:ajaxRequest('play.php?action=playSelect&amp;favorite_id=21&amp;menu=favorite',evaluateAdd);" onMouseOver="return overlib('Play');" onMouseOut="return nd();">New (/exports/mp3/new-list-local.m3u)</a></td>
	
	<td></td>
	
	<td><a href="[favorite.php?action=deleteFavorite&amp;favorite_id=21&amp;sign=2Vv_ubBiJSDEkdXAPSLihK1OZdEJAfXwm-jYvp_x](view-source:http://mp3.house/favorite.php?action=deleteFavorite&favorite_id=21&sign=2Vv_ubBiJSDEkdXAPSLihK1OZdEJAfXwm-jYvp_x)" onClick="return confirm('Are you sure you want to delete favorite: New (/exports/mp3/new-list-local.m3u)?');" onMouseOver="return overlib('Delete');" onMouseOut="return nd();"><i class="fa fa-times-circle fa-fw icon-small"></i></a></td>
	
	<td><a href="[favorite.php?action=editFavorite&amp;favorite_id=21](view-source:http://mp3.house/favorite.php?action=editFavorite&favorite_id=21)" onMouseOver="return overlib('Edit');" onMouseOut="return nd();"><i class="fa fa-pencil fa-fw icon-small"></i></a></td>
	
	<td></td>
</tr>
```

**Comment by tomchiverton** [comment] 2023-05-26 10:17
```
==> /var/log/php-fpm/www-error.log <==
[26-May-2023 11:15:25 Europe/London] PHP Fatal error:  Uncaught TypeError: sort(): Argument #1 ($array) must be of type array, string given in /home/ompd/favorite.php:156
Stack trace:
#0 /home/ompd/favorite.php(156): sort('ACK_ERROR_UNKNO...', 6)
#1 /home/ompd/favorite.php(40): home()
#2 {main}
  thrown in /home/ompd/favorite.php on line 156
```

Appears to be a harmless error from `sort($playlists, SORT_NATURAL);` ?

**Comment by tomchiverton** [comment] 2023-05-26 10:30
I rewrote as 
```
        if ( $playlists !== 'ACK_ERROR_UNKNOWN' && count($playlists) > 0) {
                sort($playlists, SORT_NATURAL);
```
so neither count() or sort() is called unless it's not an error, and that's fixed it (for at least this theme)

**Comment by tomchiverton** [comment] 2023-05-26 10:32
MR updated

**Comment by ArturSierzant** [comment] 2023-05-29 20:32
Great you found the cause of the error and fixed it. I think that fix in `favorite.php` does the job and patch in `template.header.php` is not necessary. I merged your PR. Thanks for your effort.

BTW - what version of mpd do you have?

**Comment by tomchiverton** [comment] 2023-05-29 21:01
agree, earlier fix was symptom, not cause.

I have v1.0.7 according to the footer.

**Closed** 2024-01-17 10:41 UTC
