### ISSUE TITLE
Bug: Pause Button missing in Safari on iOS

### ISSUE THREAD

**Issue by xkonni** [ArturSierzant/OMPD#65] opened 2018-03-05 08:00 UTC
The UI works nicely in Safari on iOS, except that the _Play_/_Pause_ Button never changes to _Pause_ as can be seen in this screenshot (yes it's playing): 

![ompd_play](https://user-images.githubusercontent.com/218331/36963430-698c5c96-2053-11e8-9776-927a8428e58b.png)

Thanks for your help!

**Comment by abcnorio** [comment] 2018-03-20 19:53
I can confirm this not just for Safari on iOS (had the possibility to check on different devices):

- ipad 1st gen Safari + Chrome
- iphone 4 Safari + Chrome
- Samsung Galaxy Note 10.1 Android Browser + Chromium
[probably some more device...]

However, it works e.g. on Moto G (lineage OS 14.1) and on the computer (Firefox, Chromium under win7 or Linux Debian with Mouse, no touchscreen).

The problem is reproducible.

Tapping on the play button one sees shortly a rectangle, but nothing happens. If one stays longer on it, the song plays from the beginning. A workaround would be to add a PAUSE button next to the PLAY button, because all other buttons work perfectly, so it seems this is related to "switching from one state to the other" and maybe rooted in older browsers (?). But a little bit difficult as there is no opportunity to stop mpd.

Thanks!

**Comment by xkonni** [comment] 2018-03-21 08:31
Hey abcnorio,

thanks for your tests and added information! 
Just a quick hint, you can long press the play button for stop and that also works in safari on iOS. 

greetings

**Comment by abcnorio** [comment] 2018-03-21 09:42
Hey xkonni,

thanks, yes, but this does not work constantly. Sometimes it results in the song playing from the beginning and sometimes it does nothing at all. Very seldom it works, ie. not constantly, and this is true for all the devices mentioned. I think an additional PAUSE button would solve it, because one time presses always work.
However, once I actually saw the "PAUSE" button on ios/ Safari, but only once, and it was not possible to reproduce it. Actually it should be visible as soon as the song plays, right? Maybe this is some kind of overlay problem? ie. the wrong button in front and visible and if pushed/ touched, it behaves like pushing the PLAY button because this is "active?

best wishes

**Comment by abcnorio** [comment] 2018-03-22 08:44
...another comment, instead of adding another button it could be done like the "repeat" button:

-> push button ->mark "red" + stop/pause music
-> push again -> unmark "red" + play again.

best regards

**Comment by ArturSierzant** [comment] 2018-03-22 22:41
Hi,
thank you for your tests and suggestions. Unfortunately, I don't own any Apple devices to investigate the problem. But I took a look at play/pause/stop functions, did some changes and committed them on GitHub ( 9c20001). It's rather quick and dirty solution, but please give it a try. If it won't help, I'll try to fix it other way.

**Comment by abcnorio** [comment] 2018-03-23 20:02
Hij Artur,

hey that's amazing! Tried out on all outlined devices (ios and android kitkat) and it works for me. Many thanks! And - btw - it looks pretty cool.

Question - is there an manageable way as a non-programmer to tweak the 'quick search' categories (naturally, everyone searches for different topics)? I assume you search for tags, right? Which file is it so I can have a look whether some copy & paste can do the trick.

Thanks again! o!mpd is really great and I love most that it does not add another OS but just works on an OS!! so it can be combined with other server features, etc.

best wishes

**Comment by ArturSierzant** [comment] 2018-03-27 20:24
Hi abcnorio,

the only way to tweak 'quick search' is to edit `include/config.inc.php`. You can find more info at O!MPD web page: http://ompd.pl/quick-search.

In case of doubts just let me know - I'll try to explain.

Best regards.

**Closed** 2018-07-09 17:04 UTC
